{
	"data": "ENC[AES256_GCM,data:BnoPy6AstaVGkH00ibyqEdXrYUaEsr29ptruRdMSw3+ST9YCQ1rOuVhs4aSxSI0v4l7flPBZjGzwSIdtQ1L2xvaZRV2OHfKqQOIL/tlUvMIWBzu83prZxdW8dFDRj7yvyIWxgtfkfGekngZ8RSRwOBKxUAFf3drWfAkPOY/oYTfUeaXUaJFZubdl/07ptjEyr3QVczvhdn7/HGnLQp4kWyyprmafVTSQoJnys64HFt0iOlkwxNRRmU9NYMBqi0pEJI29W78HhAO3cLjc7E3erxRvpiXOkMBLgJwWEPwiP0Gvfg+AbI0Dd1IB8kVU6BlgYU4TdYFcfAfbQ/YoqFOkEEmo1UyOEdE3LW7DCnICXA/HtHA2DuUfVlENOs0jrPv9C/yZCSL3I1XDdWlwwcjsYC6XwkzHr0M7aPN6uPVYArRTNzRn1+KvZb74nyYPR3XSX2F0lTtZRlL13PgXKd2D5bUVKej9XSXOinas48xtyK1nIn/aFSCQJpCqi3K4uiuRfZnfJ6AODkHN9A7inzaSBbJs5DGuHCiqHAku0cVFnSCiwj79o62QV6s29Ctv57qpn9E+FiQP36WY0GxQR/vmPf7uQ3GnRL3V8+pBgqqTRiOZPI0HeDcgA8xbPxoacfsOfvuDbLhNiFz6a9KcUStySXlLq4FCFMVA6hQNZtrK7+nNBmkvv8iYzKhq02iEmju/jw2/SLlneiDXvG/GJMjIRqxxWuUibgMLtgb9IT03y+3aIRJrcRoI9x5XJgsp+FhJUZvsPWS2R7bR1niZQI2eObVDqdgNzoochS6z,iv:LGnwmsyF6mWM+eovJRZNn3AMtI278XHVVct6UCuTIEY=,tag:9kDwm+9ISYwP0DfLMI13nw==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1j2lyxxhxj0g2fw05h8c856fjxy2f0salxlk78pwglpv2nxjm3ptsgxcce4",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dzJMbXBpZTZrQXBxOU9Y\nTUlYZzdmdEk1UnoxbjJ2ejZibEQ1OHRvekNVCm80bGhUeDJxNEsyeS9Gb1VJL2U1\nMUtDcEc2a3p0clQzbTBva0tNVS9udGcKLS0tIFNXUmQzd1lRRDlkMXpiSjkxV0pI\ndnQ1SER0ZFYrc3VaaXMvRWNkMGg2TjAK1z7lZdbULC/4UYtNaMH+azC+/rve7DPf\n3EWMue9Wzy/RbeYZf3A5v7/+rirP+2+A23q6jSKrqkYvq/Rc1ZE+Xw==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age14vhzajp8xemrjzqh9gzf6rpy0sckf3sa4vfdf5u60xgrktnfxc0sx85uj6",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OTRia1RueWVJWDBrbVNU\nSkhnVVpDRk96SkhvTVBTYjN1ckE4WUcrSkZVCjFpVkhTd0ZtTnlPVUZ4U1lhUTZr\nUUlEYWVNNEp2MWgzVjFGa0FqMmxqWFUKLS0tIHI3WE8rRStlUnJTS2c0UlR0TCtD\naHo5ZHZJdlVwMGF5a1h4TzdVR3hxR0EKVpwY7Rq894frCluPV3PvCuq8XYhkBEq7\nDsLfRqs0h7t5FtmmGZzVeIkrODWjR0RIzzmKqtyoc7Q7hiwpZVpLFg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1wzdqusx4v0wpn7lgda4x4tw3qkd4jlcyy89pxrh4g679m0ajadtsh49e6t",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU1ZxTVNKRm44OGh6ci9G\nN2JkcVV4UTRtQkNGaUNZNWRtNVEyRHNtaHlJCkxSTHVncHAxbUY2K2t5Y1NHUXdB\ndHNSSzMxN0IyZ1hwaW9QSkpqTHRXQW8KLS0tIGhOZU9mR0ZMU0NNM2pOL0pDeXlG\nVWJsdVU5N01mSGVpcjliK1QzSUFHSzgKxRK3nvnoVYxJ7oG5smdZBHxIefBkJ+qX\n9VpQQOyPdlrW4XHiKr1yReY+vkBtAkp5ifuAp0sZ96UDh6SccgGidg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1qepnuljqzftv5sg72nj4wt0njcnezvnlhsq0dg8zqls5e2twzuwsyxklww",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZFhBNWczR0JiTVd1RVox\nZ2RqbFlXMFQ3UkZxVU01TVFYU2F1L1JWc0I4CmRNK1M1U1ptWis1YXRaVXRKNHNJ\nOUtETTQ0WVZvNG9PQ1F2elRHS1RhbUkKLS0tIC9EdXRqQUVyYjBlRjRLRm9KNFJY\nSDhNK0Jsak1QUll6bGttaXN0RnVQME0KrByAvYTEdwA1hpidCd//282s4bI5CZTQ\nz6XHWYRH8Cn+XVi2LTedp3lrnKWGkNFrzWQx3JJ9+OeuQ1Nks11ObA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-01-16T11:26:09Z",
		"mac": "ENC[AES256_GCM,data:mNjw18xy5KGx2afwV5yYDnpiQ6ivyotUK+M2uQinBCCMO7ZK+pgae4WFqhHq8JSw7uUQ8iLzx1kFKrokEVKRQBBQOc8P1Bhi4iX/u/bb5cwT/u8iEZQUmWbEZ3AzKfBuFS03biJLMvjfhZzak+0K/XJRA2FtLcIZUtOGFaPfJSU=,iv:xvqmsMrruR7c/lA+cNcmvFP3hCQ8KPCaemcRKMSyvsM=,tag:brA1y2nS/StVk/q7h6tlqg==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.11.0"
	}
}
