{
	"data": "ENC[AES256_GCM,data:TRmpIOk07DPD1D3kurOYUobSQpJcDKxaTmJ9S2sCsp1zcVg8z1VkIXc8PHRokHv4bpgTdWvsWqmN8HLYv+x9+CWlRAtOQDhcek2n3QsIs3q2DAqtifkpboQ5LR8qCraWFFsts7UVizUeeNj4KlC7YX0Gm98SAG9LP8+1eZx7+qnpcdxE4LylNVHKDkdksE6trL7vta7QXj0p7KdwjIvi7gv7zSoSLqYe2T3CuuFQ0QLQVRR+6zDRxOLPzSnOriQbveoL1helRGGGFMylP/e8eOH3gc1F0UWmpw0sQndAiMyMk1OIDtZRXI6iS6OX3SePlE7/nIR7ufzzr9MVsDIqW8uNjX86MDmWe2ioUO5mPxg2W73594zuuoLnpkiijAjD+b70wl7vPkqe07ZVa7zI2E/xZixBbCH9eKY+2yHPam2bxBSP/ZRru8sSRe0oRTluH7PaRckhua1duKXm+P2NBw6WEFYnlvfYNXc0ZAYqyi59dsc6/xn/Sxv89S2DACgNXug/f013GoDr9Z+tS8T2drp6pLq7vjgzsNpYXbut7/gY+sQ2JlFtzRigTDmhZOlt8L9hCLpTvBKd8WTLfjYhoF1rbnfZGO1yLsk=,iv:OnMkxoSibxVWkIrYdXsSphcZm4ZX4Q4v56Lb8pnEFXU=,tag:cq8Xv1eWEUpOcF5WXHHkiQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1j2lyxxhxj0g2fw05h8c856fjxy2f0salxlk78pwglpv2nxjm3ptsgxcce4",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dzJMbXBpZTZrQXBxOU9Y\nTUlYZzdmdEk1UnoxbjJ2ejZibEQ1OHRvekNVCm80bGhUeDJxNEsyeS9Gb1VJL2U1\nMUtDcEc2a3p0clQzbTBva0tNVS9udGcKLS0tIFNXUmQzd1lRRDlkMXpiSjkxV0pI\ndnQ1SER0ZFYrc3VaaXMvRWNkMGg2TjAK1z7lZdbULC/4UYtNaMH+azC+/rve7DPf\n3EWMue9Wzy/RbeYZf3A5v7/+rirP+2+A23q6jSKrqkYvq/Rc1ZE+Xw==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age14vhzajp8xemrjzqh9gzf6rpy0sckf3sa4vfdf5u60xgrktnfxc0sx85uj6",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OTRia1RueWVJWDBrbVNU\nSkhnVVpDRk96SkhvTVBTYjN1ckE4WUcrSkZVCjFpVkhTd0ZtTnlPVUZ4U1lhUTZr\nUUlEYWVNNEp2MWgzVjFGa0FqMmxqWFUKLS0tIHI3WE8rRStlUnJTS2c0UlR0TCtD\naHo5ZHZJdlVwMGF5a1h4TzdVR3hxR0EKVpwY7Rq894frCluPV3PvCuq8XYhkBEq7\nDsLfRqs0h7t5FtmmGZzVeIkrODWjR0RIzzmKqtyoc7Q7hiwpZVpLFg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1wzdqusx4v0wpn7lgda4x4tw3qkd4jlcyy89pxrh4g679m0ajadtsh49e6t",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU1ZxTVNKRm44OGh6ci9G\nN2JkcVV4UTRtQkNGaUNZNWRtNVEyRHNtaHlJCkxSTHVncHAxbUY2K2t5Y1NHUXdB\ndHNSSzMxN0IyZ1hwaW9QSkpqTHRXQW8KLS0tIGhOZU9mR0ZMU0NNM2pOL0pDeXlG\nVWJsdVU5N01mSGVpcjliK1QzSUFHSzgKxRK3nvnoVYxJ7oG5smdZBHxIefBkJ+qX\n9VpQQOyPdlrW4XHiKr1yReY+vkBtAkp5ifuAp0sZ96UDh6SccgGidg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1qepnuljqzftv5sg72nj4wt0njcnezvnlhsq0dg8zqls5e2twzuwsyxklww",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZFhBNWczR0JiTVd1RVox\nZ2RqbFlXMFQ3UkZxVU01TVFYU2F1L1JWc0I4CmRNK1M1U1ptWis1YXRaVXRKNHNJ\nOUtETTQ0WVZvNG9PQ1F2elRHS1RhbUkKLS0tIC9EdXRqQUVyYjBlRjRLRm9KNFJY\nSDhNK0Jsak1QUll6bGttaXN0RnVQME0KrByAvYTEdwA1hpidCd//282s4bI5CZTQ\nz6XHWYRH8Cn+XVi2LTedp3lrnKWGkNFrzWQx3JJ9+OeuQ1Nks11ObA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-01-12T12:58:14Z",
		"mac": "ENC[AES256_GCM,data:utxuSn8TEB/8yuwYSULCY9+w6D4aMjdJc/nIDnTBIufHoeOA2foMysf0m/zWHeDZ2OLtWMcqlvwDK8IwsXOOa6mnucv+c+sxx3c+15euXvw3O44cpjZtUZyN4O1Gszv6GAZ/A8baGwaPlrM795BMOY3yXu4fFyIoGl4toYy9iOo=,iv:n1VbRW6R6eEtjLuRVhNDN1YiyCGC5WbagaM3lSvxq5Y=,tag:qx9usG7a9ZnGZm8ImTU9Mw==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.11.0"
	}
}
